const blockExplorer = {
  arbitrum: "https://arbiscan.io/address/",
  avalanche: "https://explorer.avax.network/address/",
  ethereum: "https://etherscan.io/address/",
  binance: "https://bscscan.com/address/",
  optimism: "https://optimistic.etherscan.io/address/",
  fantom: "https://ftmscan.com/address/",
  polygon: "https://polygonscan.com/address/",
  "zkSync Era": "https://explorer.zksync.io/address/",
  solana: "https://explorer.solana.com/address/",
  "polygon zkEVM": "https://zkevm.polygonscan.com/address/",
  cronos: "https://cronos.org/explorer/address/",
  xdai: "https://gnosis.blockscout.com/address/",
  metis: "https://explorer.metis.io/address/",
  boba: "https://bobascan.com/address/",
  base: "https://basescan.org/address/",
  functionX: "https://explorer.functionx.io/address/",
  moonbeam: "https://moonbeam-explorer.netlify.app/address/",
  aptos: "https://aptoscan.com/address/",
  bitcoincash: "https://blockchair.com/bitcoin-cash/address/",
  sui: "https://suiexplorer.com/address/",
  near: "https://explorer.near.org/address/",
  celo: "https://explorer.celo.org/address/",
  onus: "https://explorer.onuschain.io/address/",
  moonriver: "https://blockscout.moonriver.moonbeam.network/address/",
  telos: "https://teloscan.io/account/",
  algorand: "https://algoexplorer.io/address/",
  aurora: "https://explorer.aurora.dev/address/",
  kava: "https://explorer.kava.io/address/",
  pulse: "https://scan.pulsechain.com/address/",
  terra: "https://finder.terra.money/address/",
};

export default blockExplorer;
